### ISSUE TITLE
Installation procedure

### ISSUE THREAD

**Issue by amitkatti** [dnknth/ldap-ui#10]
Hi,

Trying to install this on a clean ubuntu machine and this is the error I get:

```
root@iam01:~/ldap-ui# make run
.venv3/bin/hypercorn -b 0.0.0.0:5000 app:app
make: .venv3/bin/hypercorn: Command not found
make: *** [Makefile:14: run] Error 127
```

Here is the settings.py

```
import os

# App settings
PREFERRED_URL_SCHEME = 'https'
SECRET_KEY = os.urandom( 16)

# LDAP settings
LDAP_URL = os.environ.get( 'LDAP_URL', 'ldap://192.168.10.30')
BASE_DN = os.environ.get( 'dc=test,dc=site,dc=com') # Always required
assert BASE_DN, "BASE_DN environment variable must be set"

SCHEMA_DN = 'cn=subschema'

# Attribute to check for user login
LOGIN_ATTR = os.environ.get( 'LOGIN_ATTR', 'uid')

# Binding
#
# If the two following attributes are set in the environment,
# the UI will NOT ask for a login.
# You need to secure it otherwise!
BIND_DN = os.environ.get( 'cn=admin,dc=test,dc=site,dc=com')
BIND_PASSWORD = os.environ.get( 'Password')

# Optional user DN pattern string for authentication,
# e.g. "uid=%s,ou=people,dc=example,dc=com".
# This can be used to authenticate with directories
# that do not allow anonymous users to search.
BIND_PATTERN = os.environ.get( "uid=%s,ou=people,dc=test,dc=site,dc=com")

# Searches
SEARCH_PATTERNS = ( # for search field
    '(%s=%%s)' % LOGIN_ATTR,
    '(cn=%s)',
    '(gn=%s)',
    '(sn=%s)',
)
SEARCH_QUERY_MIN = 2 # Minimm length of query term
SEARCH_MAX = 50 # Maximum number of results
```

Maybe I am missing something. I am trying to use this instead of phpldapadmin and is exactly what I am looking for. Lightweight, simple and easy to use.

**Comment by dnknth** [comment]
Added hypercorn to `requirements.txt`. Please pull and try again.

**Comment by amitkatti** [comment]
I get assertion error: BASE_DN environment variable must be set. 

```
root@iam01:~/ldap-ui# make run
.venv3/bin/hypercorn -b 0.0.0.0:5000 app:app
Running on 0.0.0.0:5000 over http (CTRL + C to quit)
Traceback (most recent call last):
  File "/root/ldap-ui/.venv3/lib/python3.8/site-packages/quart/config.py", line 168, in from_object
    path, config = instance.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".venv3/bin/hypercorn", line 8, in <module>
    sys.exit(main())
  File "/root/ldap-ui/.venv3/lib/python3.8/site-packages/hypercorn/__main__.py", line 177, in main
    run(config)
  File "/root/ldap-ui/.venv3/lib/python3.8/site-packages/hypercorn/run.py", line 34, in run
    worker_func(config)
  File "/root/ldap-ui/.venv3/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 210, in asyncio_worker
    app = load_application(config.application_path)
  File "/root/ldap-ui/.venv3/lib/python3.8/site-packages/hypercorn/utils.py", line 54, in load_application
    module = import_module(import_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/ldap-ui/app.py", line 9, in <module>
    app.config.from_object( 'settings')
  File "/root/ldap-ui/.venv3/lib/python3.8/site-packages/quart/config.py", line 171, in from_object
    instance = importlib.import_module(instance)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/ldap-ui/settings.py", line 10, in <module>
    assert BASE_DN, "BASE_DN environment variable must be set"
AssertionError: BASE_DN environment variable must be set
make: *** [Makefile:14: run] Error 1
```

What do I need to enter in the below syntax on settings.py?

import os

# App settings
PREFERRED_URL_SCHEME = 'https'
SECRET_KEY = os.urandom( 16)

# LDAP settings
LDAP_URL = os.environ.get( 'LDAP_URL', 'ldap://192.168.10.30')
BASE_DN = os.environ.get( 'ou=people,dc=example,dc=com') # Always required
assert BASE_DN, "BASE_DN environment variable must be set"

SCHEMA_DN = 'cn=subschema'

# Attribute to check for user login
LOGIN_ATTR = os.environ.get( 'LOGIN_ATTR', 'uid')

# Binding
#
# If the two following attributes are set in the environment,
# the UI will NOT ask for a login.
# You need to secure it otherwise!
BIND_DN = os.environ.get( 'cn=admin,ou=people,dc=example,dc=com')
BIND_PASSWORD = os.environ.get( 'mypassword!')

# Optional user DN pattern string for authentication,
# e.g. "uid=%s,ou=people,dc=example,dc=com".
# This can be used to authenticate with directories
# that do not allow anonymous users to search.
BIND_PATTERN = os.environ.get( "uid=%s,ou=people,dc=example,dc=com")

# Searches
SEARCH_PATTERNS = ( # for search field
    '(%s=%%s)' % LOGIN_ATTR,
    '(cn=%s)',
    '(gn=%s)',
    '(sn=%s)',
)
SEARCH_QUERY_MIN = 2 # Minimm length of query term
SEARCH_MAX = 50 # Maximum number of results

**Comment by dnknth** [comment]
From the README:

LDAP access is controlled by these environment variables:

* LDAP_URL: connection URL (optional), defaults to ldap:///).
* BASE_DN: search base (required), e.g. dc=example,dc=org.
* LOGIN_ATTR: User name attribute (optional), defaults to uid.

These should be set in the OS environment, e.g.:
    `BASE_DN=dc_example,dc=com make run`

**Comment by amitkatti** [comment]
I set the BASE_DN. 

I was asking about syntax for line 10. Do I change anything there or leave that as is?

`assert BASE_DN, "BASE_DN environment variable must be set"`

**Comment by dnknth** [comment]
The syntax is OK, it works over here.

**Comment by amitkatti** [comment]
OK thanks. Trying again.

**Comment by amitkatti** [comment]
OK - no luck. We're going to have to use phpldapadmin looks like. Thanks again for assisting
