### ISSUE TITLE
Python 3.9 makes error, specify lower python version

### ISSUE THREAD

**Issue by maxswjeon** [dnknth/ldap-ui#11]
**docker-compose.yml**
```
version: '3'
services:
  manager:
    image: dnknth/ldap-ui
    container_name: ldap_admin
    restart: always
    environment:
      - LDAP_URL=ldaps://openldap
      - BASE_DN=dc=codingbear,dc=kr
    ports:
      - 2200:5000
```

**docker-compose logs -f**
```
ldap_admin  | Running on 0.0.0.0:5000 over http (CTRL + C to quit)
ldap_admin  | Traceback (most recent call last):
ldap_admin  |   File "/usr/lib/python3.9/site-packages/hypercorn/asyncio/run.py", line 244, in _run
ldap_admin  |     loop.run_until_complete(main)
ldap_admin  |   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
ldap_admin  |     return future.result()
ldap_admin  |   File "/usr/lib/python3.9/site-packages/hypercorn/asyncio/run.py", line 139, in worker_serve
ldap_admin  |     await lifespan.wait_for_startup()
ldap_admin  |   File "/usr/lib/python3.9/site-packages/hypercorn/asyncio/lifespan.py", line 47, in wait_for_startup
ldap_admin  |     await self.app.startup()  # type: ignore
ldap_admin  |   File "/usr/lib/python3.9/site-packages/quart/app.py", line 1703, in startup
ldap_admin  |     async with self.app_context():
ldap_admin  |   File "/usr/lib/python3.9/site-packages/quart/ctx.py", line 176, in __aenter__
ldap_admin  |     await self.push()
ldap_admin  |   File "/usr/lib/python3.9/site-packages/quart/ctx.py", line 163, in push
ldap_admin  |     _app_ctx_stack.push(self)
ldap_admin  |   File "/usr/lib/python3.9/site-packages/quart/local.py", line 50, in push
ldap_admin  |     self._task_local.stack = stack = []  # type: ignore
ldap_admin  |   File "/usr/lib/python3.9/site-packages/quart/local.py", line 23, in __setattr__
ldap_admin  |     self._storage[TaskLocal._task_identity()][name] = value
ldap_admin  |   File "/usr/lib/python3.9/site-packages/quart/local.py", line 35, in _task_identity
ldap_admin  |     task = asyncio.Task.current_task()
ldap_admin  | AttributeError: type object '_asyncio.Task' has no attribute 'current_task'
ldap_admin  |
ldap_admin  | During handling of the above exception, another exception occurred:
ldap_admin  |
ldap_admin  | Traceback (most recent call last):
ldap_admin  |   File "/usr/bin/hypercorn", line 8, in <module>
ldap_admin  |     sys.exit(main())
ldap_admin  |   File "/usr/lib/python3.9/site-packages/hypercorn/__main__.py", line 177, in main
ldap_admin  |     run(config)
ldap_admin  |   File "/usr/lib/python3.9/site-packages/hypercorn/run.py", line 34, in run
ldap_admin  |     worker_func(config)
ldap_admin  |   File "/usr/lib/python3.9/site-packages/hypercorn/asyncio/run.py", line 212, in asyncio_worker
ldap_admin  |     _run(
ldap_admin  |   File "/usr/lib/python3.9/site-packages/hypercorn/asyncio/run.py", line 247, in _run
ldap_admin  |     _cancel_all_tasks(loop)
ldap_admin  |   File "/usr/lib/python3.9/site-packages/hypercorn/asyncio/run.py", line 255, in _cancel_all_tasks
ldap_admin  |     tasks = [task for task in asyncio.Task.all_tasks(loop) if not task.done()]
ldap_admin  | AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'
ldap_admin exited with code 1
```

By [asyncio update](https://docs.python.org/3/whatsnew/3.7.html#asyncio) changes made
```
The new asyncio.current_task() function returns the currently running Task instance, and the new asyncio.all_tasks() function returns a set of all existing Task instances in a given loop. The Task.current_task() and Task.all_tasks() methods have been deprecated. (Contributed by Andrew Svetlov in bpo-32250.)
```

Maybe specifying the version will help?

**Comment by Dmitry1987** [comment]
tried to use it instead cli, looks like a nice tool. 
got this error too.

**Comment by dnknth** [comment]
Fixed dependencies in the `Dockerfile`. Please try again.

**Comment by dnknth** [comment]
Hi @Dmitry1987 and @maxswjeon, please re-test and let me know.

**Comment by maxswjeon** [comment]
Works well.
