### ISSUE TITLE
Hypercorn runtime error

### ISSUE THREAD

**Issue by kahvis** [dnknth/ldap-ui#17]
Debian 11

python3-minimal=3.9.2-3
make=4.3-4.1
python3-pip=20.3.4-4
python3-ldap=3.2.0-4+b3
libsasl2-dev=2.1.27+dfsg-2.1
python-dev-is-python3=3.9.2-1
libldap2-dev=2.4.57+dfsg-3
libssl-dev=1.1.1k-1+deb11u1
python3-minimal=3.9.2-3

super@***:~/ldap-ui$ make
python3 -m venv --system-site-packages .venv3
.venv3/bin/pip3 install -U pip
Requirement already satisfied: pip in ./.venv3/lib/python3.9/site-packages (20.3.4)
Collecting pip
  Using cached pip-21.2.4-py3-none-any.whl (1.6 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.3.4
    Uninstalling pip-20.3.4:
      Successfully uninstalled pip-20.3.4
Successfully installed pip-21.2.4
.venv3/bin/pip3 install wheel
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.34.2)
.venv3/bin/pip3 install -r requirements.txt
Collecting Hypercorn==0.5.4
  Using cached Hypercorn-0.5.4-py3-none-any.whl (42 kB)
Collecting python-ldap==3.2.0
  Using cached python_ldap-3.2.0-cp39-cp39-linux_x86_64.whl
Collecting Quart==0.6.13
  Using cached Quart-0.6.13-py3-none-any.whl (78 kB)
Collecting wsproto>=0.14.0
  Using cached wsproto-1.0.0-py3-none-any.whl (24 kB)
Collecting typing-extensions
  Using cached typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Collecting pytoml
  Using cached pytoml-0.1.21-py2.py3-none-any.whl (8.5 kB)
Collecting h11
  Using cached h11-0.12.0-py3-none-any.whl (54 kB)
Collecting h2>=3.1.0
  Using cached h2-4.0.0-py3-none-any.whl (57 kB)
Collecting pyasn1-modules>=0.1.5
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting pyasn1>=0.3.7
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting click
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting itsdangerous
  Using cached itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting jinja2
  Using cached Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting blinker
  Using cached blinker-1.4-py3-none-any.whl
Collecting sortedcontainers
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting aiofiles
  Using cached aiofiles-0.7.0-py3-none-any.whl (13 kB)
Collecting multidict
  Using cached multidict-5.1.0-cp39-cp39-manylinux2014_x86_64.whl (151 kB)
Collecting hyperframe<7,>=6.0
  Using cached hyperframe-6.0.1-py3-none-any.whl (12 kB)
Collecting hpack<5,>=4.0
  Using cached hpack-4.0.0-py3-none-any.whl (32 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.0.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
Installing collected packages: hyperframe, hpack, h11, wsproto, typing-extensions, pytoml, pyasn1, MarkupSafe, h2, sortedcontainers, pyasn1-modules, multidict, jinja2, itsdangerous, Hypercorn, click, blinker, aiofiles, Quart, python-ldap
Successfully installed Hypercorn-0.5.4 MarkupSafe-2.0.1 Quart-0.6.13 aiofiles-0.7.0 blinker-1.4 click-8.0.1 h11-0.12.0 h2-4.0.0 hpack-4.0.0 hyperframe-6.0.1 itsdangerous-2.0.1 jinja2-3.0.1 multidict-5.1.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 python-ldap-3.2.0 pytoml-0.1.21 sortedcontainers-2.4.0 typing-extensions-3.10.0.2 wsproto-1.0.0
touch .venv3
QUART_APP=app.py QUART_ENV=development \
	.venv3/bin/python3 .venv3/bin/quart run
Running on https://127.0.0.1:5000 (CTRL + C to quit)
[2021-09-30 08:57:54,247] ASGI Framework Lifespan error, continuing without Lifespan support
Traceback (most recent call last):
  File "/home/super/ldap-ui/.venv3/bin/quart", line 8, in <module>
    sys.exit(main())
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/quart/cli.py", line 204, in main
    cli.main(args=args, prog_name=name)
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/quart/cli.py", line 150, in main
    return super().main(*args, **kwargs)
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/quart/cli.py", line 159, in run_command
    app.run(
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/quart/app.py", line 1346, in run
    run_single(self, config, loop=loop)  # type: ignore
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/hypercorn/asyncio/run.py", line 126, in run_single
    loop.run_until_complete(worker_serve(app, config))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/hypercorn/asyncio/run.py", line 139, in worker_serve
    await lifespan.wait_for_startup()
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/hypercorn/asyncio/lifespan.py", line 47, in wait_for_startup
    await self.app.startup()  # type: ignore
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/quart/app.py", line 1703, in startup
    async with self.app_context():
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/quart/ctx.py", line 176, in __aenter__
    await self.push()
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/quart/ctx.py", line 163, in push
    _app_ctx_stack.push(self)
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/quart/local.py", line 50, in push
    self._task_local.stack = stack = []  # type: ignore
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/quart/local.py", line 23, in __setattr__
    self._storage[TaskLocal._task_identity()][name] = value
  File "/home/super/ldap-ui/.venv3/lib/python3.9/site-packages/quart/local.py", line 35, in _task_identity
    task = asyncio.Task.current_task()
AttributeError: type object '_asyncio.Task' has no attribute 'current_task'
make: *** [Makefile:10: debug] Error 1

**Comment by dnknth** [comment]
Hello @kahvis, please try again and let me know if the issue is resolved.

**Comment by dnknth** [comment]
Closing due to lack of feedback
(but it works at my end)
