### ISSUE TITLE
ldap-ui error with AD LDAP servers

### ISSUE THREAD

**Issue by HQuest** [dnknth/ldap-ui#45]
docker logs below. Test environment is a 2016 DC level. Tried with both the whole domain and just the users DN set as base_dn.

> [2023-10-07 02:21:36 +0000] [1] [INFO] 192.168.0.10:52656 - - [07/Oct/2023:02:21:36 +0000] "GET /api/tree/base 1.1" 500 265 "http://docker:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47"
[2023-10-07 02:21:36,914] ERROR in app: Exception on request GET /api/tree/base
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/quart/app.py", line 1489, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/quart/app.py", line 1514, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/quart/app.py", line 964, in handle_user_exception
    raise error
  File "/usr/lib/python3.11/site-packages/quart/app.py", line 1512, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/quart/app.py", line 1557, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 106, in wrapped_view
    resp = await view(**values)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 120, in wrapped_view
    data = await connected(authenticated(view))(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 46, in wrapped_view
    data = await view(**values)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 77, in wrapped_view
    return await view(**values)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 188, in tree
    return await _tree(basedn, scope)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 194, in _tree
    return [ { 'dn': dn,
           ^^^^^^^^^^^^^
  File "/app/app.py", line 195, in <listcomp>
    'structuralObjectClass' : attrs['structuralObjectClass'][0].decode(),
                              ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'structuralObjectClass'

**Comment by dnknth** [comment]
As mentioned in the README, the app was only tested against OpenLdap. It seems that AD uses a different set of operational attributes than OpenLdap. The UI expects `dn`, `structuralObjectClass` and `hasSubordinates` for the tree view which threw the error.

I could try to fix this given the correct names of operational attributes for AD. You could look them up with something like:

    docker  run --rm -it dnknth/ldap-demo ldapsearch -LLLx -s base -b <AD base DN> -H ldap://your.ad.host/ +

But then, you might run into the next error even with a fixed tree view.

**Comment by HQuest** [comment]
Thanks for responding. I am aware of your limited testing. This is not a dealbreaker by any means. It is just me trying to play with a very helpful and handy web-based LDAP client tool, on my personal lab and for my own convenience, whenever I don't have an active Powershell/RDP connection to a Windows machine.

Now, ran a ldapsearch command and the only returned value is the dn: attribute. No structuralObjectClass and/or hasSubordinates attributes returned.

> $ ldapsearch -LLLx -s base -b "dc=domain,dc=com" -H ldap://server.domain.com/ -D "CN=LDAP Service Account,CN=Managed Service Accounts,DC=domain,DC=com" -W +
Enter LDAP Password:
dn: dc=domain,dc=com
>
>$ _

I'm more than happy to run a few more tests and simulations for you, as required. If you feel like going deeper on this yourself, you can always grab a 6-month free trial of any Windows Server image and deploy it locally. Plus, setting up an AD server is a no-brainer: get the OS installed, add the AD role, follow Microsoft's next-next-finish steps and the AD server is up and running in a matter of minutes.

Thanks again. Feel free to take whatever action you feel like on this report, including closing it - no hard feelings. And thank you again for the time developing this superb tool :)

**Comment by HQuest** [comment]
Hi there.

On a positive note, while the hasSubordinate attribute does not exist (as I previously stated), the structuralObjectClass indeed exist (contrary to my previous statement). It is a read only, constructed and hidden by default attribute from the MS AD tool, with values "domain, domainDNS, top".

Now, /api/schema gets a 500 Internal Server Error with the below message:

> 000020D6: SvcErr: DSID-03100836, problem 5012 (DIR_ERROR), data 0
: Operations error

While reviewing a PCAP of the transaction above, the first search made after a successful bind is for baseObject "cn=subschema", which returns the above error message. Not sure if this [[MS-ADTS]: subSchema | Microsoft Learn](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/68d2bb5e-764a-48ec-9841-a5fa429c4556) documents helps somehow, but this baseObject object seems to exist on the MS AD tree; it is just being failed to be searched somehow.

A second search is made for all the baseObjects on the BASE_DN, and 49 attributes are returned, although not displayed likely because of the above error message.

Hope this helps. Let me know next steps.

**Comment by dnknth** [comment]
Hello,

On startup, the app triggers several LDAP requests:

1. A `whoami` operation, this seems to have worked because otherwise nothing else would have.
2. A search with scope `BASE` on `cn=subSchema` (which is configured in `settings.py`). Apparently AD won't lack you have it, possibly due to lack of read privileges for normal users.
3. A search on the base DN with scope `BASE`, which succeeded in your case, but then the rendering failed due to lack of operational attributes
4. Another search on the base DN with scope `ONLEVEL` for the initial tree content. You never got that far.

(3) could be easily worked around by (a) requesting the `structuralObjectClass` by name (maybe the `+` syntax is OpenLdap specific) and using normally redundant `ONELEVEL` queries in case there is no `hasSubordinates` attribute. It would be a bit slower but work the same.

Now, item (2) is the real problem because the editor requires a schema to work. Maybe the app needs better error handling for this, but it will fail all over the place without schema information. So, unless there is a way to configure AD to deliver it, this app is probably not the right tool to access AD.
