### ISSUE TITLE
Missing Attribute

### ISSUE THREAD

**Issue by guenhter** [dnknth/ldap-ui#63]
Hi,

thank you for this project. Really appreciate that. 

Unfortunately, after I did an update to the most recent version (I had a older one which was some moths old), I'm getting this error:

```
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/usr/lib/python3.12/site-packages/starlette/_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "/usr/lib/python3.12/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/authentication.py", line 48, in __call__
    |     await self.app(scope, receive, send)
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |          ^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "/usr/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/ldap_ui/app.py", line 97, in dispatch
    |     return await call_next(request)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |          ^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "/usr/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/ldap_ui/app.py", line 153, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 20, in __call__
    |     await responder(scope, receive, send)
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 39, in __call__
    |     await self.app(scope, receive, self.send_with_gzip)
    |   File "/usr/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 460, in handle
    |     await self.app(scope, receive, send)
    |   File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/usr/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/ldap_ui/ldap_api.py", line 160, in entry
    |     _entry(request.app.state.schema, await get_entry_by_dn(connection, dn))
    |   File "/usr/lib/python3.12/site-packages/ldap_ui/ldap_api.py", line 95, in _entry
    |     must_attrs, _may_attrs = schema.attribute_types(ocs)
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/ldap/schema/subentry.py", line 377, in attribute_types
    |     object_class = self.sed[ObjectClass][object_class_oid]
    |                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
    | KeyError: 'posixAccount'
    +------------------------------------
```

any idea?

**Comment by dnknth** [comment]
Looks like you tried to navigate to some directory entry with auxiliary objectClass `posixAccount`. When trying to determine the mandarory and optional attributes for editing, an error comes from the `python-ldap` library.  When opening a similar entry in my directory, I do not get an error.

Can you share the directory schema which is available under the `/api/schema` URL? I'd like to compare it with mine.

**Comment by guenhter** [comment]
Sure. Here the file. 

[schema.json](https://github.com/user-attachments/files/17574867/schema.json)

**Comment by dnknth** [comment]
Strange, no `posixAccount` is listed there. Is the `nis` schema loaded? What happens when adding something like the following LDIF (modify the DN to match your base DN) with `ldapadd`?

```ldif
dn: cn=test,dc=example,dc=com
cn: test
gidNumber: 1999
homeDirectory: /home/test
objectClass: inetOrgPerson
objectClass: posixAccount
sn: test
uid: test
uidNumber: 1999
```

**Comment by guenhter** [comment]
This is my ldif file

```
### Groups

# Group
dn: dc=example,dc=org
dc: example
objectClass: top
objectClass: domain

# Group
dn: ou=users,dc=example,dc=org
objectClass: organizationalUnit


### Users

# Admin
dn: cn=admin,ou=users,dc=example,dc=org
gidNumber: 1999
homeDirectory: /home/admin
objectClass: inetOrgPerson
objectClass: posixAccount
sn: admin
uid: admin
uidNumber: 1999
userPassword: ldap
```

and this my compose file:

```
version: "3"

services:
  openldap:
    image: bitnami/openldap:latest
    ports:
      - 2389:1389
      - 2636:1636
    volumes:
      - ./ldifs:/ldifs:ro
    environment:
      BITNAMI_DEBUG: "true"
      LDAP_ROOT: "dc=example,dc=org"
      LDAP_SKIP_DEFAULT_TREE: "yes"
      LDAP_ALLOW_ANON_BINDING: "no"

  ldap-ui:
    image: dnknth/ldap-ui:latest
    depends_on:
      openldap
    environment:
      LDAP_URL: "ldap://openldap:1389"
      BASE_DN: "dc=example,dc=org"
      BIND_PATTERN: "cn=%s,ou=users,dc=example,dc=org"
    ports:
      - 5000:5000
```

**Comment by dnknth** [comment]
I am surprised that you got that far given that the compose file does not validate and also given that `LDAP_ALLOW_ANON_BINDING` prevents `ldap-ui` from starting up. After fixing both, the directory is reachable from `ldap-ui` but does not seem to recognise the `cosine` and `nis` schemas. Suggesting to fix that, it seems to be a directory inconsistency and not an `ldap-ui` issue.

**Comment by guenhter** [comment]
HI,

I'm using `podman compose`, so maybe this is the reason the compose file works for me.
About the Rest: does this mean this is a problem with openldap?

**Comment by dnknth** [comment]
No, found the root cause. Fix is underway.

**Comment by dnknth** [comment]
Please pull the latest image and try again.

**Comment by dnknth** [comment]
Did it work?

**Comment by guenhter** [comment]
Thank you so much. This works like a charm.
